// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPKxm6AdQwEdDmea5TGp-HlF1iaayAf9w',
    appId: '1:1009574820017:web:74ce2efbc4a812bca3ca90',
    messagingSenderId: '1009574820017',
    projectId: 'shikhshasetu',
    authDomain: 'shikhshasetu.firebaseapp.com',
    storageBucket: 'shikhshasetu.firebasestorage.app',
    measurementId: 'G-LL2XFL5FQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ivrMM6PIsEn7fcnhGB2U787Ocnp2p_Y',
    appId: '1:1009574820017:android:b05a59b38dd4ec48a3ca90',
    messagingSenderId: '1009574820017',
    projectId: 'shikhshasetu',
    storageBucket: 'shikhshasetu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKrvte9Z4ytTharBDEmc7ayyDT9lEKn1I',
    appId: '1:1009574820017:ios:8e9a583a840cd52ca3ca90',
    messagingSenderId: '1009574820017',
    projectId: 'shikhshasetu',
    storageBucket: 'shikhshasetu.firebasestorage.app',
    iosBundleId: 'com.apps.shikshasetutution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKrvte9Z4ytTharBDEmc7ayyDT9lEKn1I',
    appId: '1:1009574820017:ios:8e9a583a840cd52ca3ca90',
    messagingSenderId: '1009574820017',
    projectId: 'shikhshasetu',
    storageBucket: 'shikhshasetu.firebasestorage.app',
    iosBundleId: 'com.apps.shikshasetutution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPKxm6AdQwEdDmea5TGp-HlF1iaayAf9w',
    appId: '1:1009574820017:web:a0071c781ed219f4a3ca90',
    messagingSenderId: '1009574820017',
    projectId: 'shikhshasetu',
    authDomain: 'shikhshasetu.firebaseapp.com',
    storageBucket: 'shikhshasetu.firebasestorage.app',
    measurementId: 'G-X7S03SY289',
  );

}